### ISSUE TITLE
Couldn't load plugin 'ee_plugin'   AttributeError: 'PosixPath' object has no attribute 'rstrip' 

### ISSUE THREAD

**Issue by kennorris49** [gena/qgis-earthengine-plugin#100]
Not sure this is a new issue, so apologies if it isn't. Ubuntu 18.04 QGIS 3.16.9-Hannover
Can anybody help? I have no idea. Herewith the message:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ken/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 5, in 
    import pkg_resources
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in 
    @_call_aside
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    for dist in working_set
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3279, in 
    for dist in working_set
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/ken/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2201, in _handle_ns
    loader = importer.find_module(packageName)
  File "", line 423, in _find_module_shim
  File "", line 1223, in find_loader
  File "", line 1268, in find_spec
  File "", line 60, in _path_join
  File "", line 60, in 
AttributeError: 'PosixPath' object has no attribute 'rstrip'

**Comment by gena** [comment]
Looks like some python installation problem vs QGIS, somehow it searches for python 3.6 in your home while QGIS 3.18 uses python 3.7. Can you try the newer version? Maybe also upgrade local python

**Comment by kennorris49** [comment]
Thanks but I have Python 3.8.10. Not sure about 'local' version.

**Comment by kennorris49** [comment]
OOps. my mistake. That was another machine. I will upgrade from python
3.6.9 and try again.
Thanks
